# Generated by Django 3.1 on 2021-08-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='restaurant',
            new_name='product',
        ),
    ]
